apiVersion: apps/v1
kind: Deployment
metadata:
  name: registersystemapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registersystemapi
  template:
    metadata:
      labels:
        app: registersystemapi
    spec:
      containers:
      - name: registersystemapi
        image: canabrava/registersystemapi:latest
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: registersystemapi-service
spec:
  type: NodePort
  selector:
    app: registersystemapi
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: registersystemapi-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: registersystemapi
  ports:
  - name: registersystemapi
    protocol: TCP
    port: 8080
    targetPort: 80